### ISSUE TITLE
Updated quests

### ISSUE THREAD

**Issue by GrokDuckFarmer** [kreezxil/god-block#14]
Updated ftbquests folder for God Block.

Changes:
1) Added Inert Seed to the second Hearth Well chapter
2) Updated Mystcraft rewards to all give out random Mystcraft pages 
3) Updated quest text the Mystcraft chapter to correctly state how to make a linking book for returning (Here is wisdom)
4) Updated Astral Sorcery beginning quest to trigger on visiting the Hunting Dimension rather than obtaining marble.

[ftbquests.zip](https://github.com/kreezxil/god-block/files/3225463/ftbquests.zip)

**Comment by kreezxil** [comment]
added
