### ISSUE TITLE
[please fix] Quest process error

### ISSUE THREAD

**Issue by Hexblood** [kreezxil/god-block#15]
**Describe the bug**
The quest "Dust that Burns" says to cook Heavy Metal nuggets in a furnace to get the dust from them that burns as fuel. However, according to JEI you get it by dropping the Crushing Block on the nuggets. The Crushing Block does not come in till the following quest.

**To Reproduce**
N/A, issue is with quest instructions and processes. 

**Screenshots**
N/A

**Versions:**
 - Minecraft: 1.12.2
 - Forge: 14.23.5.2838
 - Mod Pack : 1.8.9
 - Mod Name: N/A
 - Mod Version: N/A

**Additional context**
N/A

**Comment by GrokDuckFarmer** [comment]
[ftbquests.zip](https://github.com/kreezxil/god-block/files/3245551/ftbquests.zip)

Updated the quests in the following way:
* Swapped "Smashing Things" and "A Dust that Burns" quests with each other
* Updated dependencies so route correctly
* Updated text to better explain what needs to be done and to make the quest flow read better.
* Now with 104% more ducks

**Comment by kreezxil** [comment]
thanks grok, this will be in today's update.
