### ISSUE TITLE
[please fix] Another Quest order issue

### ISSUE THREAD

**Issue by Hexblood** [kreezxil/god-block#16]
**Describe the bug**
The quests "Warm Core" and "Nether Crystal" seem to be out of order. You need the Nether Crystal to make the Warm Core but the quest for it comes after.

**To Reproduce**
N/A, issue is with quest order.

**Screenshots**
N/A

**Versions:**

 - Minecraft: 1.12.2
 - Forge: 14.23.5.2838
 - Mod Pack : 1.9.10
 - Mod Name: N/A
 - Mod Version: N/A

**Additional context**
N/A

**Comment by GrokDuckFarmer** [comment]
[ftbquests.zip](https://github.com/kreezxil/god-block/files/3263970/ftbquests.zip)

Fixed by reversing the two quests.

**Comment by kreezxil** [comment]
in latest version 1.10.11
