### ISSUE TITLE
[please fix] invalid quest rewards for Heavy Ingot.

### ISSUE THREAD

**Issue by metalim** [kreezxil/god-block#20]
**Describe the bug**
For Heavy Ingot you get choice of non-existent torches.

**To Reproduce**
Play on official server.

**Screenshots**
![](https://puu.sh/E0EWW/3ce2a16537.png)
![](https://puu.sh/E0F2P/56070f7166.png)

**Versions:**
 - Mod Pack : 1.11.12

**Comment by GrokDuckFarmer** [comment]
I see that invalid reward on the server, but not on my single player world.  That tells me the server quest files are slightly out of sync with what I handed to Kreezxil.  Also, there are three obvious broken parts of quests from previous versions.  See attached images.
![2019-08-03_06 42 34](https://user-images.githubusercontent.com/22861790/62412708-34271880-b5bb-11e9-803f-0266ba870c78.png)
![2019-08-03_06 42 39](https://user-images.githubusercontent.com/22861790/62412709-34271880-b5bb-11e9-87fc-78f249ded033.png)
![2019-08-03_06 42 46](https://user-images.githubusercontent.com/22861790/62412710-34271880-b5bb-11e9-9ac8-b6de8f7c0424.png)

**Comment by GrokDuckFarmer** [comment]
[ftbquests.zip](https://github.com/kreezxil/god-block/files/3463885/ftbquests.zip)

Attached is an updated FTBQUESTS.ZIP file that does not have the items outlined in red in the above screenshots when playing single player.  It also includes two extra fixes:
* Text for the Inert Seed quest
* Proper spelling for "Quartz" in another.

**Comment by kreezxil** [comment]
thank you

**Comment by kreezxil** [comment]
fixed in todays version
