### ISSUE TITLE
[please fix] five word description explaining it

### ISSUE THREAD

**Issue by Angelus022695** [kreezxil/god-block#22]
**Describe the bug**
JEI doesn't show up so you can't see any of the crafting recipies making the pack unplayable

**To Reproduce**
just try opening JEI

**Screenshots**

**Versions:**

 - Minecraft:
 - Forge:
 - Mod Pack :
 - Mod Name:
 - Mod Version:

**Additional context**

**Comment by kreezxil** [comment]
You sir have a corrupted pack install. This is a fault of Twitch. Delete the pack form your launcher and then reinstall fresh. Also, I saw what you did on my github chat connected tracker in discord, not cool at all.

**Comment by kreezxil** [comment]
thank you for this report.

**Comment by kreezxil** [comment]
but don't go react with FAIL next time. that is one way to make someone go on the edge.

**Comment by kreezxil** [comment]
it's because you hit CTRL+o (oh, not zero)
