### ISSUE TITLE
Sugarcane recipe is missing

### ISSUE THREAD

**Issue by xanderhunter** [kreezxil/god-block#23]
In the most recent update the recipe for sugarcane from hearth well is missing from the pack.  Originally it was 1 seed/sapling and 1 mutation paste to make sugar cane but now it seems mutation paste isnt used to craft anything other then inert seeds.

**Comment by LeapInSoft** [comment]
I have check Hearth Well code and currently you can't add recipe for the mutator.
I don't see any way in the pack for have sugar cane and paper (maybe I'm wrong)

**Comment by kreezxil** [comment]
added a recipe for sugar cane, will be available in the next update due out in about 2 hours or less.

**Comment by kreezxil** [comment]
if you look at sugar cane you will see that I created a recipe for it. so
you now have a way to make it.
