### ISSUE TITLE
[Question] Adding craft for Grains of Infinity in 1.13.19 is intentional ?

### ISSUE THREAD

**Issue by LeapInSoft** [kreezxil/god-block#25]
Hello,
Just want to know if it is intentional adding a craft for the Grains of Infinity ? I found the idea to go other dimension for get it fine (and not really too complex).
But if it is intentional I'm fine with it :)

**Comment by kreezxil** [comment]
I thought it was an issue. I'll remove it next patch.

**Comment by kreezxil** [comment]
fixed in todays version
