### ISSUE TITLE
Duplicate Cobblestone/Dirt recipes with 1.3.4

### ISSUE THREAD

**Issue by GrokDuckFarmer** [kreezxil/god-block#3]
With 1.3.4, Nothingness now drops more items, and new recipes were added for dirt and cobblestone, but the previous recipes are still there.  The old recipes are cheaper than the new ones.

**To Reproduce**
1. Log into God Block
2. Type "dirt" into the JEI search bar and click on the dirt block to see its recipe

**Screenshots**
![dirt](https://user-images.githubusercontent.com/22861790/55851665-6c878000-5b0e-11e9-9dcd-5cf23c02c60d.jpg)

**Versions:**

 - Minecraft:
 - Forge: forge-14.23.5.2824
 - Mod Pack 1.3.4

**Comment by kreezxil** [comment]
thanks, I knew it was there, the duplicate is in the scripts/ folder for
the pack. I have to remove it now. Because the mod now comes with some
starter recipes.

**Comment by kreezxil** [comment]
fixed in 1.4.5
