### ISSUE TITLE
Choice reward instead of random reward for Crushing Block

### ISSUE THREAD

**Issue by GrokDuckFarmer** [kreezxil/god-block#4]
The reward for making the Crushing Block in the Seed of Life chapter is a Choice Reward instead of a Random Reward like the Hearth Well quests.

**To Reproduce**
1. Complete the quest chain up to making the Crushing Block.
2. Click on rewards
3. Note that it is a choice reward that allows you to select the Nether star.  The pool of options looks to be the same as in the Random Reward set.

**Versions:**
 - Minecraft: 1.12.2
 - Forge: forge-14.23.5.2824
 - Mod Pack 1.3.4

**Comment by kreezxil** [comment]
here's hoping that while you were figuring out the quest lines editing that
you also figured out how to edit the reward tables. Looks like I'll be
editing god block today.

**Comment by kreezxil** [comment]
fixed. I removed the nether star and set it to random.

**Comment by GrokDuckFarmer** [comment]
I like the nether star as a very random reward.  Lots of quanta in there to make it pretty rare.

**Comment by GrokDuckFarmer** [comment]
Oh, and I didn't notice the choice reward until after I had finished playing with the quests and posted my work.
