### ISSUE TITLE
Void world should be a real void

### ISSUE THREAD

**Issue by GrokDuckFarmer** [kreezxil/god-block#5]
The only blocks that should appear in the initial dimension should be Nothingness blocks.

**To Reproduce**
1. Start a new God Block world.
2. Look around once you load in.
  -- Tinker's slime islands
  -- Tech Reborn oil pools
  -- Astral Sorcery structures (up at the top)
  -- Snow up at top (in cold biomes after it rains)

**Versions:**
 - Minecraft: 1.12.2
 - Forge: forge-14.23.5.2824
 - Mod Pack: 1.3.4

**Additional context**
I'm not at my machine to verify, but I think the Nothingness doesn't extend all the way to build height.  That would explain what the AS stuff appears up at the top, as well as snow.  I'm guessing that you can't get snow to appear above build height, but that's just a guess.

**Comment by GrokDuckFarmer** [comment]
**config\tconstruct.cfg** file needs to be updated to have the following:

B:generateSlimeIslands=false

That will remove all islands from spawning.  Another option is to change the following to add the Overworld (0) to the blacklisted dimensions:

    # Prevents generation of slime islands in the listed dimensions
    I:slimeIslandBlacklist <
        -1
        0
        1
     >

I prefer the latter since that allows slime islands to appears in Mystcraft dimensions.

**config\teamreborn\techreborn\world.cfg** needs to be updated with the following:

oil_lakes {
    # Enable the generation of underground oil lakes [Default=true]
    B:enable=false

**config\voidislandcontrol.cfg** needs to be updated with the following for a changed Nothingness Overworld dimension:

S:worldGenSpecialParameters=1;240*thegodblock:thenothing

This puts enough air blocks at the top of the world so Astral Sorcery can create structures that will not be cut off.  Since there is no way to whitelist the dimensions by number with the vast number Mystcraft may produce, the only way to access the astral sorcery structures is to have them appear in the Overworld.  Even on a server, with 10k blocks between players' islands, there are plenty of AS structures for people to fine.

I have tested these changes (slime island black list, not B:generateSlimeIslands=false) to see a much more void-like Overworld.  There are a few AS structures, but when I write up an Astral Sorcery quest line, I'll hang a lampshade on it by writing how the AS god has sprinkled the Nothingness with his structures to help you along.

**Comment by kreezxil** [comment]
I've implemented all this, except that I'm allowing the astral structures to generate in the nether and the end so actually there was a way to allow them to generate somewhere else.
