### ISSUE TITLE
[feature request] Remove grass and iron and gold recipes from God Block mod

### ISSUE THREAD

**Issue by GrokDuckFarmer** [kreezxil/god-block#6]
Since Hearth Well has a way to make iron and gold blocks, it doesn't make sense to be able to use the Nothingness drops to make iron and gold ingots.

**Describe the solution you'd like**
For the the God Block modpack, the God Block mod recipes for iron and gold ingots should be disabled.  Likewise, the Seed of Life will make grass around it, so the grass block recipe should be removed in the God Block modpack.  Grass blocks is not nearly as game breaking as the iron and gold ingots are.

**Comment by kreezxil** [comment]
ok, all of this deactivated in the new version
