### ISSUE TITLE
Book of the Well cannot be crafted

### ISSUE THREAD

**Issue by GrokDuckFarmer** [kreezxil/god-block#8]
Currently there is no way to craft the Book of the Well to see in-game documentation for Hearth Well.

**Repro steps:**
1. Start a new God Block world.
2. Search for Book of the Well in JEI and look for the recipe.

**Expected:**
I can craft the book and read the information inside.

**Actual:**
The book has no visible recipe.  While there is a wiki I can look at, I much prefer in-game documentation.  The book is implemented via the Patchouli mod, and I notice that the patchouli_books folder under God Block is empty.  This makes me think the book would be empty even if I could create it.

**Versions:**
 - Minecraft: 1.12.2
 - Forge: forge-14.23.5.2836
 - Mod Pack: 1.5.6

**Comment by kreezxil** [comment]
it probably is, it was working on an ealier release of hearthwell

**Comment by kreezxil** [comment]
Apparently there is now a ritual to attain it. https://github.com/wolforcept/hearthwell/issues/16

**Comment by kreezxil** [comment]
the recipe was added by my guys before you, according to wolforce in his channel, you were never meant to craft it.

**Comment by kreezxil** [comment]
confirmed the book can not be crafted. It must be obtained thru a ritual. the questline should outline that.
